### PR TITLE
add call method

### PR DESCRIPTION
**Pull request by shenchao591**
for this pr,[https://github.com/koajs/compose/pull/104](url)

### CODE REVIEW

**Comment by dead-horse** [comment]
can you provide more informations for this change?

**Comment by jonathanong** [comment]
@dead-horse this adds `this` support in middleware

@shenchao591 can you add a test?

**Comment by dead-horse** [comment]
> this adds this support in middleware

because we prefer to use arrow functions which will lose `this` in middleware, I think a uniform use of `ctx` is a better choice.

**Comment by dead-horse** [comment]
close for now.

**Pull request closed without merging**
