### PR TITLE
Add Telegram link

### PR DESCRIPTION
**Pull request by nooks**

### CODE REVIEW

**Comment by juliangruber** [comment]
i joined this channel but can't post to it. what's the story?

**Comment by nooks** [comment]
Telegram announced the bot for the channel. I want to set up automatic publication releases Telegram channel

**Comment by juliangruber** [comment]
ok, i'd then hold of merging this until the channel becomes useful

**Comment by dead-horse** [comment]
please change the target branch to `v2.x`.

**Comment by jonathanong** [comment]
@nooks will you be updating this?

**Comment by tejasmanohar** [comment]
@jonathanong It seems that you still can't talk in the Telegram channel for [this reason](https://github.com/koajs/koa/pull/601#issuecomment-159232445), and you have to open a new PR to change the target branch on a GitHub PR so really no point keeping this one open.

**Pull request closed without merging**
