### PR TITLE
Fix issue when app.use() is called with empty value

### PR DESCRIPTION
**Pull request by yanickrochon**
PR supersedes #590

### CODE REVIEW

**Comment by dead-horse** [comment]
d134fff9e82d050e81bf579a693ed2114e7946c6 landed

**Comment by yanickrochon** [comment]
The point of keeping `debug` before the `if` is to know what is being passed. At the moment, an error is thrown, however there is no debug information telling what is being passed. My PR did solve that without losing any information.

**Comment by dead-horse** [comment]
it will just debug `use -` when passing `null` or `undefined` to `app.use`. Throw an error is enough.

**Comment by yanickrochon** [comment]
Well, then, the line should be `debug('use %s', fn && (fn._name || fn.name) || JSON.stringify(fn));` or something. The point of debugging is to debug, otherwise it would be called `info()` or `notice()`. Justifying throwing an error without actually know what value caused the error makes the `debug` call pointless in these cases.

**Comment by juliangruber** [comment]
because of https://github.com/koajs/koa/commit/d134fff9e82d050e81bf579a693ed2114e7946c6#diff-5372f626ee15242f1e2c6eb31655b4faL103 the debug call will always see a function only

**Comment by yanickrochon** [comment]
Some middleware are dynamically generated functions. In some applications, this may result in `undefined` to be returned and passed to `app.use`. There *is* a `debug` call, but it is after checking `fn`. So, in case of error being thrown, `debug` will not specify what value is actually being passed. Unless the error message is modified with `throw new TypeError('middleware must be a function, ` + String(fn) + ' given!');` or something, some information is missing.

**Pull request closed without merging**
