### PR TITLE
add experimental async function support

### PR DESCRIPTION
**Pull request by jonathanong**
requires `regenerator` or `6to5` to actually use. enabled by setting `app.experimental = true`. it's probably going to be a lot slower. if we merge this, i'd like to get feedback on https://github.com/thenables/composition. maybe add a benchmark with it.

closes https://github.com/koajs/koa/issues/339

### CODE REVIEW

**Comment by tj** [comment]
nice! LGTM

**Comment by fengmk2** [comment]
Wow, how much slow using async function right now?

**Comment by jonathanong** [comment]
I don't know. Benchmark it!

**Comment by juliangruber** [comment]
awesome work, jonathan!

**Comment by fixe** [comment]
cool.

**Comment by cesarandreu** [comment]
Any benefits to using async functions over generators at this time?

**Comment by jonathanong** [comment]
Probably won't be any benefits until v8 supports, optimizes, and supports stack traces on async functions

**Comment by ruimarinho** [comment]
Nice one :+1: @jonathanong you should change `6to5` to `babel` as it has been renamed.

**Comment by jonathanong** [comment]
done:D

**Pull request merged**
