### PR TITLE
Return middleware chain promise from `callback()`

### PR DESCRIPTION
**Pull request by PlasmaPower**
Without this, there's no way of hooking into after Koa is done with the response. This can be extremely important if used with `ctx.respond = false`, as in #846 (see there for use case). While this is technically a breaking change, I don't expect it to break anything.

### CODE REVIEW

**Comment by dougwilson** [comment]
i.m.o. it's not really a breaking change :)

**Comment by PlasmaPower** [comment]
Yeah, the one situation I could see this breaking anything is `if (handler(req, res))`, but that shouldn't happen (hopefully). http://xkcd.com/1172/

**Comment by PlasmaPower** [comment]
> Current coverage is 100% (diff: 100%)
> Merging #847 into master will not change coverage

I don't think that's how diffs work... :smile:

**Comment by jonathanong** [comment]
can we add a test for the use-case if we add this? not opposed to it.

**Comment by nickb1080** [comment]
This is great! One thing to be aware of is that even if you do `ctx.respond = false` and then use the promise-returning API from this PR to do further processing after koa finishes with a request, there is still the fact that koa has set `res.statusCode = 404`. It's not difficult to reset that value, but you risk overwriting something in the koa app *explicitly* setting status code to `404`. Is there a way for koa to internally mark a request as "maybe send 404 if `respond` is reached" without actually changing the state of the `res` object -- seems important especially in this context, because once control is transferred back to the enclosing app, the enclosing app sees the `404` attached by koa.

**Comment by jonathanong** [comment]
> Is there a way

yes :) suggestions welcomed. i haven't thought about this yet, so feel free to make suggestions.

**Comment by PlasmaPower** [comment]
Maybe `app.usedAsMiddleware`? It would remove the default `statusCode` setting and return early [here](https://github.com/PlasmaPower/koa/blob/8836cd30d140ec285e3ceadbeadeda1f1796af24/lib/application.js#L218) (don't `res.end()` if there's nothing to send).

**Comment by PlasmaPower** [comment]
Okay, I've just added in `app.usedAsMiddleware`. Let me know how it looks and I can port it over to the v2 PR.

**Comment by jonathanong** [comment]
im ok with it. anyone else? @koajs/owners

though maybe we could use a name with only 1-2 words :P

**Comment by PlasmaPower** [comment]
Yeah a better name for the app variable would be appreciated.

**Comment by PlasmaPower** [comment]
I can rebase and pull the changes into the v2 branch if you're ready to merge.

**Comment by nickb1080** [comment]
Any updates on this?

**Comment by PlasmaPower** [comment]
If a better config name is needed, maybe `disableDefaultResponse`?

**Comment by EduardoRFS** [comment]
why not `àpp.middlewareMode` or `app.mode = 'middleware'`

**Comment by PlasmaPower** [comment]
Because that describes a common use case, not its function.

**Comment by nickb1080** [comment]
So as I look at this again, it occurs to me that instead perhaps we can be more generic. `usedAsMiddleware` is still a pretty specific name and purpose. I propose instead `app.defaultStatus` with an initial value of `404`. Thus we can end up with something like the following:

```
const app = new Koa();
console.log(app.defaultStatus); // logs "404"
app.defaultStatus = null; // override it

// main app logic and routes here
app.use(async ctx => {
  if (ctx.url !== "/user") return;
  const user = await db.getUser();
  ctx.body = user;
  ctx.status = 200; // <-- set status here
});

// final middleware, responsible for just checking if something upstream
// set a status. if so, we want to let Koa respond. otherwise, we will assume
// the outer framework will handle the request
app.use(async ctx => {
  if (ctx.status == null) {
    ctx.respond = false;
  }
});
```

This also lets us drop checking of `app.usedAsMiddleware` in the `respond` function, and we can let `ctx.respond` do it's original job.

(This all assumes we are returning the promise as already implemented in this middleware)

Thoughts?

**Comment by nickb1080** [comment]
@PlasmaPower @jonathanong any thoughts on the comment above? would love to get support for embedding Koa into existing applications merged ASAP. Happy with the current implementation if people feel it's superior to what I proposed above.

**Comment by jonathanong** [comment]
@nickb1080 yes, that looks feasible. It's been a while since I looked at this issue. if all we want to merge is `return fn.call(ctx).then(...)`, then I'm okay with that

**Comment by nickb1080** [comment]
@jonathanong How do you want to proceed? Do you want me to open a PR against `v2.x` with the single small change of adding `return`?

**Comment by fl0w** [comment]
@nickb1080 why not master?

**Comment by PlasmaPower** [comment]
Why does the branch `v2.x` still exist? It seems to be just a previous point on master.

**Comment by nickb1080** [comment]
Ah! I hadn't noticed the switchover had already happened.

**Comment by PlasmaPower** [comment]
Yeah I agree. Closing this in favor of #848.

**Pull request closed without merging**
