### PR TITLE
fix: this.body setter does not respect this.respond

### PR DESCRIPTION
**Pull request by jasonxia23**
It's easy to fix the problem, but pretty hard to write a test case, since error is thrown after the response sent, and would not close the connection.
Would be appreciate if someone can help.

### CODE REVIEW

**Comment by likegun** [comment]
I feel confused, is there a situation people want to handle response by themself and also want to set context.body in the meanwhile?

**Comment by dead-horse** [comment]
related issue: https://github.com/koajs/koa/issues/1044

**Comment by jasonxia23** [comment]
The PR is based on this issue.

**Comment by jonathanong** [comment]
can you make a test case where this is necessary? why not just check `.headerSent` instead?

**Comment by jonathanong** [comment]
closing in favor of https://github.com/koajs/koa/pull/1078

**Pull request closed without merging**
