### PR TITLE
eslint + editorconfig

### PR DESCRIPTION
**Pull request by jonathanong**
closes https://github.com/koajs/koa/issues/495

- [ ] update rules so that they are more inline with the current styles

we should be making minimal code changes. we're only extending from standard's rules since there's just a lot of good stuff there.

### CODE REVIEW

**Comment by targos** [comment]
I can help with that

**Comment by tejasmanohar** [comment]
do we want to just use standard instead? i refactored most of that in #524 and actually seems like a pretty good tool (though i don't mind either which way).

**Comment by juliangruber** [comment]
i think just anything sane that doesn't require a massive diff will work. removing all the semis seems a bit too much for what it's worth

**Comment by tejasmanohar** [comment]
@juliangruber `standard --format` removed them all for me

**Comment by jonathanong** [comment]
whoa whoa whoa that diff is ridiculous. ideally we just adjust the rules so it makes our styles consistent. not change the whole thing to standard :P

**Comment by jonathanong** [comment]
we should just make a "tj" config haha

**Comment by tejasmanohar** [comment]
lol alright, fair enough

**Comment by tj** [comment]
I just find it ironic that the "standard" is almost the complete opposite of what 90% of js devs do haha

**Comment by tejasmanohar** [comment]
@tj lol true.
- semicolons are most popular
- function name () { } , pretty sure function name() { } is most popular
etc

**Comment by targos** [comment]
@tj :+1: that's so true

**Comment by kriswill** [comment]
you could use something like https://github.com/Flet/eslint-config-semistandard/blob/master/eslintrc.json, and relax rules to taste.

**Comment by targos** [comment]
https://github.com/koajs/koa/pull/525

**Pull request closed without merging**
