### PR TITLE
Ssotomayor feature/532 content type hard not send

### LINKED ISSUE #532: 'Content-Type' hard not to send
I'm working to implement a spec that calls for a [201 Created response with no body](https://tools.ietf.org/html/draft-ietf-webpush-protocol-00#section-5). Currently Koa is giving me a application/octet-stream with a content-length of 0, which seems a little silly. I'd like some way to not send a Content-Type.

Related is #277.

### PR DESCRIPTION
**Pull request by jonathanong**
closes #532
closes #534

@dougwilson @fundon @ssotomayor how about this?

### CODE REVIEW

**Comment by ssotomayor** [comment]
Seems in the same direction as [this](https://github.com/koajs/koa/commit/cd97fccdfda606b7a59992da94df39d07270bfb6#diff-d86a59ede7d999db4b7bc43cb25a1c11R305), however as i pointed out before, i'm not sure why is `application/octet-stream` as the default option, there are even tests checking that. If there is no logical reason i support the option of setting `null` as any header option to NOT send it, then the user decides.

**Comment by fundon** [comment]
LGTM

**Comment by jonathanong** [comment]
anyone else?

**Comment by tejasmanohar** [comment]
LGTM. agree w/ @dougwilson's comment on the previous PR for this fix

**Comment by juliangruber** [comment]
+1

**Comment by fengmk2** [comment]
+1

**Comment by dougwilson** [comment]
LGTM

**Comment by tj** [comment]
@ssotomayor octet stream is a reasonable default I think, everything is an octet stream haha, but :+1:  for this

**Comment by ssotomayor** [comment]
Just closed the other PR, i agree with the fixes. :+1:

**Comment by evilive3000** [comment]
Hi. Is there a way to respond with an _undefined_ body and **DO NOT** set a _content-type_.

I'm trying to make an internal redirect by nginx depend on the headers that returned from koa's backend. All I need is only one field `X-Accel-Redirect`; but Koa appends `Content-Type: text/plain` header which will be transparently proxied through nginx. But if content-type were absent in koa's respond Nginx automatically decides what type it is and sets it correctly.

I found the code where the magic happened [application.js#L218](https://github.com/koajs/koa/blob/master/lib/application.js#L218):

```javascript
  // status body
  if (null == body) {
    body = ctx.message || String(code);
    if (!res.headersSent) {
      ctx.type = 'text';
      ctx.length = Buffer.byteLength(body);
    }
    return res.end(body);
  }
```
according to this I will always get non empty body?

**Comment by evilive3000** [comment]
Right after posting prev comment I found that if I explicitly set body to null `ctx.body = null;` I receive 204 status code as expected. Wonder why it is not default behavior. When I don't set the body shouldn't it be treated as if I set it to `null`

**Pull request closed without merging**
