### PR TITLE
support x-real-ip

### PR DESCRIPTION
**Pull request by atian25**

### CODE REVIEW

**Comment by slaskis** [comment]
I would move that code into `get ips()` instead.

**Comment by atian25** [comment]
@slaskis  if `x-forward-for[0] != x-real-ip` then ?

**Comment by slaskis** [comment]
well in your PR you prioritise `x-real-ip` anyway. So if you would add that first as the first option in `get ips()` it should have the same effect.

**Comment by atian25** [comment]
ok, so `get ips()` should add `x-real-ip` when `x-forward-for[0] != x-real-ip`.
x-real-ip = 100.100.100.100
x-forward-for = 200.200.200.200,300.300.300.300
so `get ips()` = [100.100.100.100, 200.200.200.200,300.300.300.300] ?

**Comment by tj** [comment]
sounds redundant, why not just use x-forwarded-for? from the cases I'm seeing x-real-ip == the first in x-forwarded-for

**Comment by jonathanong** [comment]
i'd also prefer if this logic was in a separate module. see:

- https://github.com/koajs/koa/issues/281
- https://github.com/jshttp/proxy-addr
- https://github.com/jshttp/forwarded

**Comment by atian25** [comment]
copy~

**Pull request closed without merging**
