### PR TITLE
use strict mode to unlock more es2015 features

### PR DESCRIPTION
**Pull request by tejasmanohar**
classes + block-scoping is only available in strict mode. also just enforces some more good code rules... that we're passing since e717733aa86efa8639745de5d179a611b5431d79

### CODE REVIEW

**Comment by jonathanong** [comment]
damn you're on a roll!!!

**Comment by tejasmanohar** [comment]
@jonathanong hehe, thx! will be giving a talk on Koa on Wednesday :sunglasses:

**Comment by jonathanong** [comment]
ooooo where at?

**Comment by tejasmanohar** [comment]
@jonathanong local meetup- http://www.meetup.com/nashjs/events/224842082/. ~1h long... will build a mini dynamic blog like [koablog-mongo](https://github.com/marcusoftnet/koablog-mongo). your [campjs talk](https://www.youtube.com/watch?v=bNVcVx8TfPc) helped me understands lots of koa :100:

**Comment by tejasmanohar** [comment]
anyhow, i'll get someone to take a video and put it up on YT

**Comment by tejasmanohar** [comment]
what i find really strange is that `const` is working fine without strict mode though the error of using `let` in strict mode is
`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`
and, the docs also say `const` is only available in strict mode https://nodejs.org/en/docs/es6/ :question: 

i assume we'll probably end up using strict mode anyways... so don't think it matters but still strange

**Comment by targos** [comment]
The spec says that both `const` and `let` should work in sloppy mode. However in V8 only `const` is currently supported. It's true that the error message is a bit misleading.
There is an issue tracking this: https://code.google.com/p/v8/issues/detail?id=3305
PR to update node doc: https://github.com/nodejs/new.nodejs.org/pull/230

On the upcoming Node.js 5.0.0, which will include V8 4.6, `let` will be available in sloppy mode behind the flag `--harmony-sloppy-let`.

**Comment by tejasmanohar** [comment]
@targos aha, makes sense! new something was up with the node docs there... clear mismatch, but nice job validating w/ spec and PR - i was too slow on that haha

to me, strict mode sounds like a good idea for koa regardless of the es2015 features

**Comment by targos** [comment]
> to me, strict mode sounds like a good idea for koa regardless of the es2015 features support in/out of it

I agree. To me, strict mode should be enabled everywhere.

**Comment by jonathanong** [comment]
ugh. let's do this against master! was gonna try to cherry-pick into master but there were too many conflicts. @tejasmanohar do you want to do this? otherwise, i can

**Comment by tejasmanohar** [comment]
@jonathanong i'll do it

**Pull request closed without merging**
