### PR TITLE
mention bluebird promise performance boost

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
If this gets merged, you might also want to create this for v2.x, where it will have an even bigger impact.

**Comment by jonathanong** [comment]
iirc correctly v2 uses `any-promise`. i'm not really willing to recommend people replace globals...

**Comment by fl0w** [comment]
Also, this won't work for anyone transpiling using babel which would require `require('babel-runtime/core-js/promise').default = require('bluebird')`.

**Comment by tj** [comment]
nothing wrong with replacing globals really, it's effectively the same thing as a replacing a singleton

**Comment by eriktrom** [comment]
Seems reasonable until native implementations are faster. It's also a good doc in general, I say merge it. If anyone is opposed to globals, just say "yeah we know it's a global monkeypatch, and x,y and z are the reasons..."

I hate when I forget to require bluebird, just in general.  Bigger than koa this does seems to be, but a good place to mention the topic it is nonetheless (as koa is popular and people may actually read these docs, spread word, etc)

**Comment by eriktrom** [comment]
> If this gets merged, you might also want to create this for v2.x, where it will have an even bigger impact.

Disagree. Very few people read .md files outside of master branch on github.

**Comment by fl0w** [comment]
@eriktrom: @PlasmaPower was talking about performance wise - as v2.x uses Promises for flow control.

**Comment by jonathanong** [comment]
no longer relevant with v2.x. thanks

**Comment by capaj** [comment]
@jonathanong I disagree that this is not relevant anymore. There has been some improvement in native promises speed, but bluebird is still way faster even when you're not using generators.

**Comment by tj** [comment]
When someone shows me that they handle over 9000 or whatever request/s on a single node which somehow magically provides HA, we can talk about adding Bluebird.

**Comment by capaj** [comment]
@tj I am not saying promises are the bottleneck. You're right, the performance gains are small and it's worthless to waste precious readme.md markdown space on this.

My disagreement was merely with a comment https://github.com/koajs/koa/pull/753#issuecomment-282463545

**Pull request closed without merging**
