### PR TITLE
Template strings

### PR DESCRIPTION
**Pull request by tejasmanohar**
PR to replace ugly string concatenation w/ nice ES6 template strings (interpolation)... I confirmed that tests pass on commit 2ae5757 (before modifying tests/*) as well as `HEAD`.

### CODE REVIEW

**Comment by tejasmanohar** [comment]
Agh snap! Looks like Node.js v0.12 doesn't support ES6 template strings with or without `--harmony`... however, io.js did at the time v0.12 was latest :cry: 

Maybe we should keep this open and possibly use for v2.0 of Koa? I imagine by that time we'd be thinking Node 4.0+? Thoughts? @tj

**Comment by thelinuxlich** [comment]
Template strings are much slower

**Comment by tejasmanohar** [comment]
@thelinuxlich if you look at the changes in context, not sure how much it'd matter... benchmarks?

**Comment by thelinuxlich** [comment]
http://kpdecker.github.io/six-speed/

**Comment by tejasmanohar** [comment]
@thelinuxlich Hm, fair. In context (please check the minor changes made), do you think the performance loss outweighs readability benefits? This kinda pushes me saying use Babel, use Babel, etc...

**Comment by targos** [comment]
There are benchmarks in the project. You can start by running them before and after your changes.

**Comment by tj** [comment]
lgtm, I'm assuming ops/s for simple string stuff is well in the millions so even if it's a tad slower that probably doesn't matter

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/commit/65ed40f40f0ec3bb15f9d132a5effff1cfca96a1!

**Comment by felixfbecker** [comment]
I also don't think template strings need to be used _everywhere_. If you just concat something like `'Invalid error code' + code` there is no need to invoke a template function. It is only beneficial if you got a huge string with lots of values or when you use tagged template strings.

**Comment by targos** [comment]
if a template string isn't tagged, it is desugarized by V8 to string concatenation. There is no function invocation. I personally think it improves readability to use them, even for small concatenations.

**Comment by tejasmanohar** [comment]
Template strings > string formatting > concatenation from a readability perspective. Tagged template strings have little to no use to us in koa itself anyways :)

**Comment by felixfbecker** [comment]
From MDN:
 > The default function just concatenates the parts into a single string

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings

 > The static String.raw() method is a tag function of template strings, similar to the r prefix in Python or the @ prefix in C# for string literals. It's used to get the raw string form of template strings (that is, the original, uninterpreted text).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw

**Pull request closed without merging**
