### PR TITLE
lint: import eslint from v2.x

### PR DESCRIPTION
**Pull request by jonathanong**

### CODE REVIEW

**Comment by jonathanong** [comment]
god damnit

repeating: 

@stevepeak hey how do i switch this over to codecov? i can't figure out why coveralls is still a status check and not codecov

**Comment by stevepeak** [comment]
I cannot answer for Coveralls, but Codecov did post a status for the commit prior and this one :+1:

**Comment by jonathanong** [comment]
oh now it's there!!!

**Comment by stevepeak** [comment]
It will set the status upon the first upload. In the near future it will post immediately upon syncing with GH. Thanks!

**Pull request closed without merging**
