### PR TITLE
non-error thrown, fixed #432

### LINKED ISSUE #432: Assert in ctx.onerror not caught
I had a promise that rejected with a string as an error instead of a proper Error object. There is an [assert in context.js](https://github.com/koajs/koa/blob/c307c81c4313e13ed8464aafbccd1544e8ecf3a8/lib/context.js#L106), but it's never caught in [application.js](https://github.com/koajs/koa/blob/c307c81c4313e13ed8464aafbccd1544e8ecf3a8/lib/application.js#L128) so both the error string and the assert are silently swallowed and no response is sent to the client.

### PR DESCRIPTION
**Pull request by dead-horse**
don't block the response

### CODE REVIEW

**Comment by jonathanong** [comment]
:+1:

**Comment by jonathanong** [comment]
you wanna make a release? or i can

**Comment by dead-horse** [comment]
i'll release 0.19.1

**Comment by fengmk2** [comment]
+1

**Pull request merged**
