### PR TITLE
remove last comma in object

### PR DESCRIPTION
**Pull request by sodawy**

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Should we add an eslint rule to enforce this?

**Comment by magicdawn** [comment]
eslint +1

**Comment by jonathanong** [comment]
yeah, style changes are pointless w/o rules to enforce it

**Comment by PlasmaPower** [comment]
Oh, master doesn't have an eslintrc? I thought it did. This is already fixed in v2.x BTW.

**Pull request closed without merging**
