### PR TITLE
Update fresh to ^0.5.2 to close vulnerability

### PR DESCRIPTION
**Pull request by hcz**
@dlebedynskyi reports in #1085:
> fresh has Vulnerable Regular Expression issue.
https://snyk.io/vuln/npm:fresh:20170908
Current version listed in package.json is 0.5
it is advised to up update to 0.5.2 for fix.

This can be fixed by updating package.json

### CODE REVIEW

**Comment by popomore** [comment]
koa use `^0.5.0` that will install 0.5.2, besides you lock the version with package-lock.json or yarn.

**Comment by iyuq** [comment]
if you install before and installed `0.5.0`, then rerun `npm i`, will the `0.5.2` be installed? If not, I think it's better to update `0.5.0` to `0.5.2`. @popomore

**Comment by hcz** [comment]
@popomore @iyuq 
`npm i` won't update previously installed fresh 0.5.0 to 0.5.2 (both with and without package-lock.json)

**Comment by popomore** [comment]
@hcz do you remove node_modules before install?

**Comment by dlebedynskyi** [comment]
this does not really impacts new koa installations without lockfiles. 

However 0.5.0 satisfies requirements. I belive that for case when lockfiles (or already installed node_modules) have 0.5.0 it will remain 0.5.0 and won't update to 0.5.2. 

One way or another appreciate looking into this guys. Update with 0.5.2 is much appreciated. At minimal it will silence `snyk dogs`

**Pull request merged**
