### PR TITLE
fix to pass the test at node v6.x

### PR DESCRIPTION
**Pull request by iyuq**
I reopened the request and squashed the 3 commits into one commit.

### CODE REVIEW

**Comment by juliangruber** [comment]
can you explain why this change is necessary for node 6? (btw +1 from me, I've never liked the implicit globals available through mocha)

**Comment by iyuq** [comment]
@juliangruber  because node v6.x's querystring is create by Object.create(null), it doesn't have the prototype of Object.prototype, so if call ctx.query.should it would throw a error.

**Comment by iyuq** [comment]
@juliangruber  see The object returned by querystring.parse() no longer inherits from Object.prototype [#6055](https://github.com/nodejs/node/pull/6055).

**Comment by juliangruber** [comment]
thank you!

**Comment by iyuq** [comment]
@juliangruber you're welcome! but why haven't it added to the master branch? I have also opened a pull request to the master branch.

**Comment by PlasmaPower** [comment]
@iyuq I'm pretty sure that PR got closed as a duplicate of this one by accident :P it shouldn't be though, they are different branches.

**Comment by iyuq** [comment]
@juliangruber  so I should reopen that PR again?

**Pull request merged**
