### PR TITLE
fix: add named function for request and response handlers

### PR DESCRIPTION
**Pull request by fengmk2**
Named function is good for APM and avoid anonymous functions everywhere.

image

image

### CODE REVIEW

**Comment by jonathanong** [comment]
:+

**Comment by fengmk2** [comment]
I'm going to merge this and pick to 2.x branch.

**Comment by fengmk2** [comment]
Oh no, v2.x is arrow function, don't touch it.

**Comment by jonathanong** [comment]
@fengmk2 i don't mind changing it to a named function declaration

**Comment by fengmk2** [comment]
@jonathanong good

**Comment by fengmk2** [comment]
Release 1.2.2 to npm

**Pull request merged**
