### PR TITLE
Return middleware chain promise from `callback()`

### PR DESCRIPTION
**Pull request by PlasmaPower**
The v2.x version of #847, see there for more details.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
I'm going to rebase this - it'll be very helpful in rewriting a test, so I hope it gets merged soon.

**Comment by PlasmaPower** [comment]
Rebased! Let me know if anything still needs done before merging. As for testing, my new jest test suite will use this feature in a test. Also, I'm not sure this is complicated enough to need it's own test.

**Comment by nickb1080** [comment]
🎉  excellent! @jonathanong -- think we can get this merged soon? Also, I'm going to experiment a bit on some patterns for mounting a Koa app inside a Connect-style app and would be happy to contribute some docs about it once I have an approach that feels right.

**Comment by PlasmaPower** [comment]
Rebased again. Anything blocking merge?

**Comment by nickb1080** [comment]
Awesome! Thanks for pushing this through @PlasmaPower @jonathanong. If there is interest I'm happy to contribute some docs on how to properly embed Koa w/in existing Connect-style app and how to do an incremental migration.

**Pull request merged**
