### PR TITLE
app.silent option to turn off err logging

### PR DESCRIPTION
**Pull request by tejasmanohar**
Solves #447 

// cc participants- @jonathanong @tj @cesarandreu

### CODE REVIEW

**Comment by tj** [comment]
lgtm

**Comment by tejasmanohar** [comment]
@tj hm, somewhere else as in #447 or elsewhere? (sorry, pretty new to koa)

**Comment by tj** [comment]
I think it's scattered a bit, some in https://github.com/koajs/koa/issues/367, and https://github.com/koajs/koa/issues/219 is somewhat related. I'll leave this open for a little if anyone else wants to give some feedback but it works for me! thanks man

**Comment by tejasmanohar** [comment]
alrighty.

are we going to consider this a breaking change? i guess it does change what logs when and based on what... so maybe breaks the API?

**Comment by travisjeffery** [comment]
Works for me too. I'm okay wither way w.r.t. to versioning, but based on expierence with other projects people tend to complain a lot even if you change logging and don't follow semver strictly.

**Comment by tejasmanohar** [comment]
@travisjeffery yeah, i think a major version would be a good idea... like 1.1

**Comment by tj** [comment]
Since it's just test related I think it would be fine, unless we leave that 'test' == check in until 2.x, doesn't really hurt

**Comment by tejasmanohar** [comment]
@tj Ah ok, you're right- would you like me to add the 'test'' env check back in AFTER the `this.silent` check? that would make it a non-breaking change.

**Comment by tejasmanohar** [comment]
i.e.
```javascript
if (this.silent) return;
if ('test' == this.env) return;
```
so codebases relying on the 'test' env to not log won't be affected by this change. in v2, we can remove the 'test' env check and make people use the silent option? @tj

**Comment by tj** [comment]
sounds great! maybe throwing in a comment so we remember to deprecate it later `// DEPRECATE (v2)` or something

**Comment by tejasmanohar** [comment]
done- 6c19c41. yay for semver!

**Comment by fengmk2** [comment]
LGTM.

**Pull request merged**
