### PR TITLE
add more error message when passed a non-generatorFunction to use

### PR DESCRIPTION
**Pull request by dead-horse**

### CODE REVIEW

**Comment by tj** [comment]
hmm we might be better off using the inspect util for some cases, might be overkill since the lineno is going to be there anyway

**Comment by dead-horse** [comment]
it is easy to exceed the limit in test cases. lol

**Comment by jonathanong** [comment]
maybe do some wonderful https://github.com/tj/callsite stuff?

**Comment by dead-horse** [comment]
I've tried to do some magic with `callsite`, but at last I found that the most important information to users is what object they passed to `app.use`.

**Comment by jonathanong** [comment]
@dead-horse what do you mean?

**Comment by tj** [comment]
I still think this impl is a little weird since we'd get `[object Object]` in some cases etc, util.format or whatever is probably better in that sense but then it starts to get super overkill IMO

**Comment by jonathanong** [comment]
hmmm i'd like to just remove this assertion...

**Comment by dead-horse** [comment]
close for now, no significant promotion.

**Pull request closed without merging**
