### PR TITLE
response.attachment append a parameter: options from contentDisposition

### PR DESCRIPTION
**Pull request by zzzs**
response.attachment require content-disposition, and content-disposition supports option parameter to make some settings, so i hope attachment can also support it.

thanks !

### CODE REVIEW

**Comment by dead-horse** [comment]
can you add a test case for this to avoid later changes modified this feature.

**Comment by zzzs** [comment]
@dead-horse thanks, already done!

**Comment by zzzs** [comment]
Ok, I will do it two days later.

**Comment by zzzs** [comment]
@fl0w already done!

**Pull request merged**
