### PR TITLE
No longer set content-length

### PR DESCRIPTION
**Pull request by Akcbryant**
The content-length header is automatically set by the http module.

### CODE REVIEW

**Comment by dougwilson** [comment]
The http module does not set content-length. You can see that by the fact that the tests for it failed. If the length is not set by Koa, then the response will be in the chunked format, adding extra bytes on the site for the chunk boundaries (and the zero length chunk at the end).

**Comment by dougwilson** [comment]
The test/application goes through the http module, so would see any headers added by it.

**Comment by Akcbryant** [comment]
Ah, I see. Thanks, this means issue #902 can be closed then?

**Comment by dougwilson** [comment]
Maybe. Hard to really know without understanding more about what drove the issue. Perhaps there is an issue somewhere that made it seem like it was from the content-length ? Not sure.

**Pull request closed without merging**
