### PR TITLE
fix Application.inspect() – missing .proxy value. Closes #563

### LINKED ISSUE #563: How to set `app.proxy`?
Hello,

I see it mentioned in the docs that you can set `app.proxy` to trust proxy header fields. I have been trying this in the following way:

```javascript
const app = koa();
app.proxy = true;
```

However, this doesn't seem to have any effect, and when I later inspect `app`, it seems the value isn't set. All I get back is: `{ subdomainOffset: 2, env: 'development' }`.

Am I missing something?

### PR DESCRIPTION
**Pull request by tj**
As mentioned in #563 we were just missing an initial value and output

### CODE REVIEW

**Comment by jonathanong** [comment]
looks good. shall i push to v1 and v2?

**Comment by tejasmanohar** [comment]
should be merged to [master](https://github.com/koajs/koa) and [v1.x](https://github.com/koajs/koa/tree/v1.x), imo, since the issue / bug exists in both. that's what the v1.x branch is for ;)

**Comment by tj** [comment]
Doesn't apply cleanly at all to 1.x, I'll patch that manually

**Comment by tejasmanohar** [comment]
sorry, yeah, i didn't mean to merge this branch to 1.x branch, just meant copying over the changes. merging would be far more work :P

**Comment by tj** [comment]
accidentally pushed it straight in to 1.x ;D peer review ftw haha

**Pull request merged**
