### PR TITLE
Update all dependencies - 02/04/2022

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
I have updated all the dependencies to the latest versions excluding `statuses` #1480 and `http-errors` #1486 .

### CODE REVIEW

**Review by 3imed-jaberi — COMMENTED** [review]
About the linter warns, fixed by this PR #1658

**Review by 3imed-jaberi — COMMENTED** [review]
@jonathanong @miwnwski @niftylettuce @fengmk2 @dead-horse 👀

**Review by 3imed-jaberi — COMMENTED** [review]
You can close these PRs: #1639, #1625 and #1624
You can merge these related PRs: #1480 and #1486

**Review by etroynov — APPROVED** [review]

**Comment by miwnwski** [comment]
We don't need to hunt these dependencies in package.json as they all are installed within semver ranges anyway.

**Pull request closed without merging**
