### PR TITLE
Lint before running test

### PR DESCRIPTION
**Pull request by robinpokorny**
To ensure code style lint should be run before testing the code.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
We already have it running in travis, at least for v2.x.

**Comment by robinpokorny** [comment]
I am aware of that but that could be quite late and frustrating for the developer. Style should be checked as soon as possible—but that is my personal opinion.

**Comment by robinpokorny** [comment]
And this is a PR to v2. As long as I know we do not lint v1.

**Comment by PlasmaPower** [comment]
@robinpokorny we recently started linting v1. Also, I'm not sure many people even run `npm test` as opposed to `make test`.

**Comment by robinpokorny** [comment]
@PlasmaPower, I see. Then this is probably useless.

The idea was that developers might not be aware of the linter, committing wrongly-styled test-passing code and discover the style does not pass only after the CI runs.

Maybe there could be a *Contributing* section/file where one would learn what should be done before submitting a PR. What do you think?

**Comment by PlasmaPower** [comment]
I agree that forgetting to lint is an issue, I often forget myself. As for a contributing file, I'm not sure that would help much more than travis and a friendly comment, especially since that I haven't seen linting fail much.

**Comment by jonathanong** [comment]
i'm -1 because if i need to lint, i'll run `npm run lint` or whatever. i'll know linting fails in CI

**Comment by robinpokorny** [comment]
I see, slowing the test down is a good argument.

Then I would just add the `npm run lint` @jonathanong mentioned and which does not exist now. WDYT?

**Comment by fl0w** [comment]
I would much rather read a contributor doc that explains what's expected and having CI follow those same guidelines.

**Comment by jonathanong** [comment]
@robinpokorny i'm fine with an `npm run lint` command.

@fl0w yes we need a contributor doc :)

**Pull request closed without merging**
