### PR TITLE
Add flag for cache body type

### PR DESCRIPTION
**Pull request by fundon**

### CODE REVIEW

**Comment by fl0w** [comment]
What would the (side?)-effects be to use use Symbols for the flags?

**Comment by fengmk2** [comment]
Better performance?

**Comment by tj** [comment]
Hrm seems super overkill to me personally

**Comment by jonathanong** [comment]
If we're improving performance we should see a benchmark.

But yeah, seems overkill to me too

**Comment by dead-horse** [comment]
it will be a breanking change if developers already use `ctx.flag` for some other usage. also export `flag` is useless here.

**Comment by fundon** [comment]
I closed it.

@dead-horse Just you said, `ctx.xxx` would be overridden.

**Pull request closed without merging**
