### PR TITLE
Link to v2.x in docs

### PR DESCRIPTION
**Pull request by rattrayalex**
A first step towards https://github.com/koajs/koa/issues/533#issuecomment-235300442

If you like the direction, let's workshop the wording and I'll add the inverse to the v2.x branch and figure out a way to clean it up on https://github.com/koajs/koajs.com . 

Sound good?

### CODE REVIEW

**Comment by jonathanong** [comment]
hmmm i'm wondering if we should host v2 on koajs.com with a link to v1 docs, which will be hosted on like koajs.com/v1

**Comment by jonathanong** [comment]
having it be on every markdown file, which combined is a single page on koajs.com, is kind of noisy. all we really need is a link

**Comment by rattrayalex** [comment]
> hmmm i'm wondering if we should host v2 on koajs.com with a link to v1 docs, which will be hosted on like koajs.com/v1

Yes, that is my hope & intention. 

> having it be on every markdown file, which combined is a single page on koajs.com, is kind of noisy. all we really need is a link

Yes, I was thinking we'd strip out those links on the html site. But presumably some people just browse the `docs` folder on github.

**Comment by jonathanong** [comment]
hi,

gonna close this as we're going to replace koajs.com docs w/ v2 docs. a PR linking to v1 docs would be great — I would just say just to link to v1.x/docs

**Pull request closed without merging**
