### PR TITLE
Refactor application.js - use arrow function in callback and remove EventEmitter from 'event' module

### PR DESCRIPTION
**Pull request by stojanovic**

### CODE REVIEW

**Comment by fundon** [comment]
Good catch!

**Comment by juliangruber** [comment]
+1

**Comment by tj** [comment]
:+1:, wonder why `(=> expr)` isn't legal :-1:

**Comment by stojanovic** [comment]
@tj I guess because of the reserved words, ie. (async => expr) wouldn't work as you expect :)

**Comment by tj** [comment]
hmm should I think that'd still be unambiguous since it's a keyword grammar-wise but I guess it does look confusing haha

**Comment by stojanovic** [comment]
Ah, but `async` is not reserved keyword yet as far as I know.
You can do `let async = 'whatever'`.
Maybe it'll be in future, but even babel let you do that at the moment.

**Comment by tejasmanohar** [comment]
that's actualyl not an issue w/ babel. it's actually intended. `async` is not going to be a reserved word / keyword due to backwards compatibility. `var async = require('async')` for example would break...

so i think it does make sense to do `() => ...` for argument-less functions (rather than `=> ...`)

**Comment by stojanovic** [comment]
Yes, you are right, I read something about that and totally forgot.

**Comment by tejasmanohar** [comment]
(that said, do note that everything isn't implemented correctly in babel... like let/const are still hoisted and binding of `this` in arrow functions isn't as straight-forward as appears)

**Pull request merged**
