### PR TITLE
Remove deprecated back

### PR DESCRIPTION
**Pull request by fl0w**
https://github.com/koajs/koa/issues/1114

Notice it being branched from [fl0w:refactor-back](https://github.com/koajs/koa/pull/1115), needs rebase post merge.

### CODE REVIEW

**Comment by niftylettuce** [comment]
Any reason besides not having someone review this yet @fl0w to not merge?  Would this go out in v3?

**Review by 3imed-jaberi — APPROVED** [review]

**Review by 3imed-jaberi — COMMENTED** [review]
@jonathanong 👀

**Comment by jonathanong** [comment]
https://www.npmjs.com/package/http-errors

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/pull/1115/files

**Pull request closed without merging**
