### PR TITLE
Add ctx.wrappers array

### PR DESCRIPTION
**Pull request by PlasmaPower**
Goes along with koajs/compose#52.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
Copied from another conversation:

If we implement this, I'd be in favor of removing the deprecated generator to promise conversion in favor of `koa-convert` providing a wrapper to convert generators to promise-based middleware. I think that would be the more versatile approach, as some people might want to use generators with the new argument syntax until async/await arrives. The current approach would convert them as if they took ctx as this instead of an argument, and you'd have to extend the Koa Application to change that.

**Comment by jonathanong** [comment]
also see https://github.com/koajs/compose/pull/51

**Comment by jonathanong** [comment]
would really love more people to express their opinions, otherwise, I'm inclined to just merge it!

**Comment by PlasmaPower** [comment]
This and #707 preform the same purpose different ways, so only one should be merged. Do you prefer this one?

**Comment by miwnwski** [comment]
I'll just close this as it has little relevance today IMO. Maybe there's still a need for wrappers but I doubt it personally and the same functionality can be approached in user land. Also, over the years I haven't really seen any requests for wrappers. If I remember correctly, this was brought to light due to TJ's original issue to simplify mw profiling, though today this can be solved with async_hooks which seems more like native approach Koa should aim towards. Please reopen if I'm wrong :)

**Pull request closed without merging**
