### PR TITLE
chore: upgrade koa-convert dependency to ^2.0.0

### PR DESCRIPTION
**Pull request by atombrenner**
fix issue #1534

### CODE REVIEW

**Review by ryouaki — APPROVED** [review]

**Comment by miwnwski** [comment]
I agree it should be upgraded (and removed in next) but this would result in a breaking change (I don't really remember why convert got bumped major, maybe you can enlighten me if you recently checked it out?).

This will have to wait to next version of Koa, though any possible next Koa dependency would actually remove this dependency.

**Comment by atombrenner** [comment]
>  (I don't really remember why convert got bumped major, maybe you can enlighten me if you recently checked it out?).

As far as I can see, the change is the dependency upgrade of koa-compose@3.2.1 to koa-compose@4.1.0 plus some more cosmetic refactorings.

**Comment by miwnwski** [comment]
Well in that case, it LGTM!

**Review by miwnwski — APPROVED** [review]

**Comment by miwnwski** [comment]
Holding off merge a little

**Review by 3imed-jaberi — APPROVED** [review]
lgtm +1 

> whisper: we must move quickly to work on next release of Koa.

**Pull request merged**
