### PR TITLE
remove outdated wiki reference

### PR DESCRIPTION
**Pull request by fl0w**
Kind of weird. The wiki reference is outdated, either update or remove the reference.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
It looks fine to me. Sure, some of the middleware doesn't support v2, but we could add a "supports v2" column or something.

**Comment by fl0w** [comment]
Alright, closing this then. I'll try to "PR" that wiki entry with a separate issue adding a support v2 column. I'll do an initial scan for compatibility.

**Comment by PlasmaPower** [comment]
@fl0w okay, makes sense. Also, for the wiki it's not a PR, just an edit that automatically goes through.

**Comment by fl0w** [comment]
@PlasmaPower aye, "PR" :) I figured I'd make changes to my fork and reference it for acceptance.

**Pull request closed without merging**
