### PR TITLE
fix: switched JSON.stringify to fast-safe-stringify

### PR DESCRIPTION
**Pull request by niftylettuce**
ref: https://github.com/davidmarkclements/fast-safe-stringify

### CODE REVIEW

**Comment by crobinson42** [comment]
My initial thoughts are hesitant to add this as a dependency. 

- what problem does it solve
- are there user issues raised about this as a concern or _issue_
- is this the best library to use to replace JSON.stringify

**Comment by dead-horse** [comment]
actually it is easy to define your own response method using `fast-safe-stringify` to serialize JSON body without change the default JSON.stringify

**Comment by niftylettuce** [comment]
@dead-horse is it possible for you to give a clean and easy example?

**Comment by dead-horse** [comment]
```js
ctx.body = safeJSON.stringify(obj);
ctx.type = 'json';
```

or you can make it as a function in `context` with a middleware?

**Comment by niftylettuce** [comment]
Yeah I meant without having to do `ctx.body = foobar` everytime.  Is there a simple way to do this?  We should possibly allow a custom stringify function to get passed?  It would also open up the door for people to "blacklist" certain properties they don't want to get sent along.

**Pull request closed without merging**
