### PR TITLE
response body setter checks headersSent

### PR DESCRIPTION
**Pull request by likegun**
related issue: [843](https://github.com/koajs/koa/issues/843)
related pr: [1060](https://github.com/koajs/koa/pull/1060)

### CODE REVIEW

**Comment by jonathanong** [comment]
thanks @likegun 

can we add a test that covers the case in #843? thanks

**Comment by jonathanong** [comment]
@likegun also make this PR for master! thanks

**Comment by likegun** [comment]
@jonathanong Thanks, but I think the test I add covered the case in [#843](https://github.com/koajs/koa/issues/843) and I will make this PR for master once this PR is merged.

**Comment by likegun** [comment]
So what going on with this pr?

**Comment by likegun** [comment]
close this pr because of this [commit](https://github.com/koajs/koa/commit/3c23aa5b74d19352e0a78d135df5ed6979d4e242)

**Pull request closed without merging**
