### PR TITLE
Allow to app.use multiple middlewares at once

### PR DESCRIPTION
**Pull request by rocketspacer**
Usage
```
app.use(foo, bar, baz)
app.use([foo], [bar, baz])
```

### CODE REVIEW

**Comment by jonathanong** [comment]
not opposed to this, but it needs tests

**Comment by rocketspacer** [comment]
@jonathanong added

**Comment by rocketspacer** [comment]
@jonathanong any news?

**Comment by fl0w** [comment]
I think this is better dealt by koa-compose. In my opinion it’s just better to let compose handle the complexity of flattening (and other resolves?), keep `Application.use` simple. I’m in favor of just removing the guards and pass whatever’s in `middleware` to compose with a flattening PR merged.

**Comment by jonathanong** [comment]
@fl0w is right, we should be doing this in `koa-compose`

**Review by 3imed-jaberi — COMMENTED** [review]
I agree with @miwnwski  (@fl0w) ✔️ +1

**Comment by niftylettuce** [comment]
v4.2.0 released of koa-compose @ https://github.com/koajs/compose/releases/tag/v4.2.0 per https://github.com/koajs/compose/pull/96

**Pull request closed without merging**
