### PR TITLE
fix to pass the test at node 6.0.0

### PR DESCRIPTION
**Pull request by iyuq**
get the test case to pass at node v6.0.0

### CODE REVIEW

**Comment by PlasmaPower** [comment]
:+1:, but I'd prefer if you squashed them into one commit

**Comment by iyuq** [comment]
is that right, I reopened a pull request and squashed them into one commit. @PlasmaPower

**Comment by juliangruber** [comment]
@PlasmaPower we can now squash during merging straight from the github ui, see https://github.com/blog/2141-squash-your-commits

**Comment by PlasmaPower** [comment]
@juliangruber Sweet! Didn't realize that.

**Pull request closed without merging**
