### PR TITLE
export HttpError from http-errors library

### PR DESCRIPTION
**Pull request by micheal-hill**
Exporting `HttpError` from the library, following the brief discussion in #1156

### CODE REVIEW

**Comment by fl0w** [comment]
Hi, thanks for helping out. If this gets merged, HttpError would be part of the Koa API. Thus, I would like to see a test making sure it in-fact is exported and available.

**Comment by rictorres** [comment]
is this really something we want exposed? i mean, if consumers are actually relying on it, changing the lib used or even updating it can/will introduce a breaking change :{

**Comment by fl0w** [comment]
@rictorres HttpError has been [thrown](https://github.com/koajs/koa/blob/v1.x/lib/context.js#L89) at least since Koa v1. I think it's safe to assume Koa's pretty much married to [http-errors](https://www.npmjs.com/package/http-errors). This addition wouldn't add anything new, and removing http-errors, without exposing it, would still require a semver major anyway.

**Comment by micheal-hill** [comment]
@fl0w I wasn't exactly sure what you were expecting to see from the tests, so I've added a couple. Please let me know if it should be changed somehow.

@rictorres see #1156
In short; my code has no direct dependency on the `http-errors` library, but I indirectly create errors of type `HttpError` by calling `assert` and `throw`. There's no functionality that Koa exposes, that I can find, which allows me to check if a thrown error is a `HttpError`.

**Comment by pcr910303** [comment]
@fl0w Are there any updates on here?̊̈ I would very much appreciate this PR 👍

**Comment by fl0w** [comment]
@dead-horse @fengmk2 any opinions on this?

**Comment by fengmk2** [comment]
LGTM. Please rebase from master and resolve the conflicts.

**Comment by fengmk2** [comment]
@micheal-hill can you resolve the conflicts? After that I will merge and release a new version.

**Comment by dead-horse** [comment]
please fix the lint error

```
/home/travis/build/koajs/koa/test/application/index.js
  80:1  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by fengmk2** [comment]
landed 2d1c5981869e0fe6f5bc71b5c5582accfd125cc6

**Comment by fengmk2** [comment]
2.9.0

**Pull request closed without merging**
