### PR TITLE
Support UNIX variants where make is not an alias for gmake

### PR DESCRIPTION
**Pull request by ilkkao**
Assuming bash is always available, this could solve #883

### CODE REVIEW

**Comment by juliangruber** [comment]
what about `alias make="gmake"` in your local shell config?

**Comment by gdams** [comment]
@juliangruber that's not a particularly good solution, it would be good to make this work on aix without any extra configuration

**Comment by tj** [comment]
I like @juliangruber's suggestion, I don't know what's going on here but seems like a hack if this were something every library needs to support.

**Comment by ilkkao** [comment]
I was thinking of making `npm test` to work out of the box on AIX. The report said that on AIX you only have GNU make.  

I don't use or care AIX myself but as the official node releases are tested with https://github.com/nodejs/citgm and Koa is one of the selected test packages, it makes sense to not let koa to fail there. Koa is still only one of the 100 test modules so changing environment just for Koa might not be that straightforward either.

I was able to minimize the change. It's definitely still a hack but affects only one line now.

**Comment by tj** [comment]
Nice the new change is not bad, though I still think delegating here is appropriate. Koa doesn't care if it's selected for some CI thing or not, that's their deal.

**Comment by ilkkao** [comment]
That also makes sense. I'll just leave this here.

**Comment by gibfahn** [comment]
The reason we have to use `gmake` (i.e. GNU make) on AIX is because koa's Makefile uses the GNU extensions to POSIX make. The ideal fix would be to go through the makefile and have it be POSIX make compliant, but if we're going to do that we might as well just rewrite the Makefile in node right?

Note that other non-Linux *nix variants will probably have the same issues as AIX.

**Comment by tj** [comment]
Fair enough, at least it's a small change now, though I can't say I've typed `gmake` in my life, too much Ubuntu/OSX I guess haha.

**Comment by gdams** [comment]
@ilkkao is this good to land now?

**Comment by ilkkao** [comment]
yes, tested on mac and fedora 24.

**Comment by gdams** [comment]
I can confirm that this works on AIX

**Comment by gdams** [comment]
This is failing for me on linux and darwin:
```
error:   failure             | The canary is dead: 
error:   failing module(s)   |                     
error:   module name:        | dbca1f21c7eaa33a37c1b136c7f9b26a19bcc233
error:   version:            |                     
error:   error:              | The canary is dead: 
error:   error:              | undefined                                                                                          
error:                       | > koa@1.2.4 test /tmp/be2b8a64-bb03-4d48-83dd-270f748855c3/dbca1f21c7eaa33a37c1b136c7f9b26a19bcc233
error:                       | > if type 'gmake' 2> /dev/null; then gmake test; else make test; fi                                
error:                       |                                                                                                    
error:                       | gmake: not found                                                                                   
error:                       |                                                                                                    
error:                       | make: *** No rule to make target `test'.  Stop.                                                    
error:                       | npm ERR! Test failed.  See above for more details.                                                 
error:   done                | The smoke test has failed.
info:    duration            | test duration: 46857ms
```

**Comment by ilkkao** [comment]
Looks like the working directory is somehow wrong. My test was:

```
~/Code> cd koa && npm test
```

If the temp directory is still around, can you check that

```
ls /tmp/be2b8a64-bb03-4d48-83dd-270f748855c3/dbca1f21c7eaa33a37c1b136c7f9b26a19bcc233
```

is koa repository root directory and includes `Makefile`?

**Comment by gdams** [comment]
I'll double check

**Comment by gdams** [comment]
yup works for me, I was installing from npm, not github

**Comment by gdams** [comment]
has there been any progress with this?

**Comment by PlasmaPower** [comment]
If #926 goes through, this won't be necessary as it doesn't use make.

**Comment by jonathanong** [comment]
https://github.com/koajs/koa/issues/703 gonna switch over to jest, which will make the test command 1 line and will make this easier to do!

**Pull request closed without merging**
