### PR TITLE
fix bug https://github.com/koajs/koa/issues/1547

### PR DESCRIPTION
**Pull request by masx200**
fix bug https://github.com/koajs/koa/issues/1547

### CODE REVIEW

**Review by 3imed-jaberi — APPROVED** [review]
LGTM 💯

**Comment by jonathanong** [comment]
will need a test for this

**Comment by masx200** [comment]
Thanks, I don't know how to write unit tests, and I'm just an amateur programmer.

**Comment by jonathanong** [comment]
actually, something we need to do here is consume any bodies, otherwise if the body was a stream, this would create a leak. this would need some more complicated checks for this code as well as existing code

**Pull request closed without merging**
