### PR TITLE
Use Jest

### LINKED ISSUE #703: Switch to a new testing system
# Frameworks

| Framework | Simultaneous Testing | Multiple Processes For Multiple Files | Global Error Handling | Builtin Babel | NPM Downloads/Month |
| --- | :-: | :-: | :-: | :-: | :-: |
| Mocha (current) |  |  | ✓ |  | NPM Downloads/Month |
| Ava | ✓ | ✓ |  | ✓ | NPM Downloads/Month |
| Jest | ✓ | ✓ |  | ✓ | NPM Downloads/Month |
# Request Libraries

| Request Library | Uses Promises | Builtin Response Testing | Response Testing Covers Common Use Cases | Reasonable Defaults For Testing | NPM Downloads/Month |
| --- | :-: | :-: | :-: | :-: | :-: |
| Superagent |  |  |  | ✓ | NPM Downloads/Month |
| Supertest (current) |  | ✓ |  | ✓ | NPM Downloads/Month |
| Supertest-As-Promised | ✓ | ✓ |  | ✓ | NPM Downloads/Month |
| Assert-Request | ✓ | ✓ | ✓ | ✓ | NPM Downloads/Month |
| Request |  |  |  | ✓ | NPM Downloads/Month |
| Request-Promise | ✓ |  |  |  | NPM Downloads/Month |
| Node-Fetch | ✓ |  |  | ✓ | NPM Downloads/Month |
| Requisition | ✓ |  |  | ✓ | NPM Downloads/Month |
# Notes
- `(current)` indicates that Koa currently uses it.
- If we use a framework with builtin babel support, we can easily use async/await in place of builtin response testing if the library supports promises.
- If a request library doesn't have reasonable defaults, we can easily create a wrapper that does.
- If the response testing doesn't cover common use cases, a custom helper assertion function can be used instead.

If anybody has any more columns or rows to add to either table, please leave a comment.

### PR DESCRIPTION
**Pull request by gillesdemey**
Inspired by https://github.com/koajs/koa/pull/926, fixes #703 and partially addresses #559

As I understand the consensus seems to be:

* Use `Jest`
* Prefer `assert`
* Keep using `supertest@3`

I used Promises / async where it made most sense and where it simplified the tests.

I'm using `--forceExit` because some tests do not properly close `app.listen`, I don't think it's that big of a deal and the current test suite has the same behaviour.

Haven't focused on making the benchmarks work cross-platform, might send a PR in the future to use [autocannon](https://github.com/mcollina/autocannon) instead of wrk (although `wrk` is fine for me, it seems some folks are concerned about the Windows platform).

### CODE REVIEW

**Comment by dead-horse** [comment]
great work!

**Comment by robinpokorny** [comment]
@gillesdemey, I was just wondering, what are the arguments for `assert`? In the issues you linked, I could not find it.

**Comment by gillesdemey** [comment]
@robinpokorny It's an alias of `assert.ok`

https://nodejs.org/api/assert.html#assert_assert_ok_value_message

**Comment by robinpokorny** [comment]
@gillesdemey Oh, I meant in comparison to `expect` that comes with Jest.

Full disclosure, I really like the new [.resolves/.rejects](http://facebook.github.io/jest/docs/en/expect.html#resolves) matchers for async code. I was about to check if it is used here and create a PR otherwise. But found out that we use `assert` everywhere. It this PR, it says ‘Prefer assert’ and I could not find the reasons for it written anywhere.

**Comment by gillesdemey** [comment]
`assert` has a much simpler interface, contrasted to `expect`'s more readable style. 

I believe @jonathanong has stated his preference for `assert` a few time before but it ultimately comes down to personal preference :)

https://github.com/koajs/koa/pull/926#pullrequestreview-27074635
https://github.com/koajs/koa/pull/926#pullrequestreview-27074635

**Comment by robinpokorny** [comment]
@gillesdemey OK, thanks. That's what I wanted to find out!

**Pull request merged**
