### PR TITLE
Remove unused http variable (v2.x)

### PR DESCRIPTION
**Pull request by PlasmaPower**
ESLint now runs fine. This is why we need eslint in travis.

### CODE REVIEW

**Comment by jonathanong** [comment]
oh shoot. is it not running in travis?

**Comment by jonathanong** [comment]
how come this isn't failing for me locally? brb `rm -rf node_modules; npm i`

**Comment by jonathanong** [comment]
oh because we aren't linting that folder

**Comment by PlasmaPower** [comment]
@jonathanong oops - was looking at master not v2.x when checking if eslint was run.

**Pull request merged**
