### PR TITLE
make default redirect status 303 in place of 302

### PR DESCRIPTION
**Pull request by chrisveness**

### CODE REVIEW

**Comment by jonathanong** [comment]
:+1: needs votes from the community!

**Comment by gabeio** [comment]
Reading on http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#10.3.4 this will break any redirects for older browsers that use http/1.0.

Personally I would rather this be a setting. If you know users are going to be using older devices or you want to support older devices it might be nice to not break this backward compatibility for no reason. As both act nearly identical.

**Comment by dougwilson** [comment]
It also breaks HTTP/1.1 browsers that didn't (yet) understand 303.

**Comment by dougwilson** [comment]
But I believe those browsers are so old, that people who need to support them can always change the setting back. I think the main thing is does the 302 -> 303 change itself make sense.

**Comment by gabeio** [comment]
Well currently looking at the code; it's not a setting is my point I'd rather see this become a setting that can be switchable and then I would agree that changing to 303 will be an okay change as they are basically the same thing.

**Comment by chrisveness** [comment]
As @dougwilson says, it's a default which can be easily overridden. The most recent references I can find relate to [Windows XP](http://support.microsoft.com/kb/947513) and [IE 3.0 / Netscape 2.0](http://stackoverflow.com/questions/535053).

**Comment by chrisveness** [comment]
Historical aside: [Alan Flavell](http://www.alanflavell.org.uk/www/post-redirect.html) (writing 10/15 years ago) sums things up rather well, to my mind: *Historically, in HTTP/1.0, status 302 (temporary relocation) was documented to call for the response that is now, in HTTP/1.1, documented for status 307. However, the popular browsers did not implement that specification: instead, they implemented the response that is now documented for status 303.*

**Comment by fengmk2** [comment]
303 is fine, but 302 is `de facto standards`, most people only know 302 and 301.
Agree with @gabeio , make redirect status to optional, defaut is 302.
Then people know about 303 they can set default status to 303.

**Comment by jansauer** [comment]
:+1: 303 sounds like a good compromise between 302 and 307. But i agree that 307 would be the right solution based on the rfc. #391

**Comment by tunnckoCore** [comment]
303 redirects don’t appear to work properly to search engines :-1: 
http://bloggingmax.net/303-redirect-and-its-effect-on-seo/ - article from February 2015

I cant understand why you need 303? And why actually is 302 not a 301.

It should be configurable with options or somthing

**Comment by gabeio** [comment]
@tunnckoCore 301 is a redirect that the browser will learn and attempt not to make the request again.
a 302 the browser will continue to keep asking the server the same request and will not learn the redirect.
303 is just a new 302...

**Comment by tunnckoCore** [comment]
> 303 is just a new 302

just, must, bust, hust.. no matter.
I cant understand whats the problem is to be setting, not by default, when SEOs stated that its not good thing. :)

**Comment by fengmk2** [comment]
I like keep `302` status for tmp redirect by default. 

:-1:

**Comment by hallas** [comment]
Let's keep it at `302` for now.

**Pull request closed without merging**
