### PR TITLE
Fix typo in docs/api/index.md

### PR DESCRIPTION
**Pull request by niczy**
s/nvm/npm

### CODE REVIEW

**Comment by jonathanong** [comment]
not a typo

**Comment by juliangruber** [comment]
@niczy `nvm`, or "node version manager", by this command installs iojs, which is the new desired platform for koa to be run on

**Comment by fengmk2** [comment]
...

nvm: https://github.com/creationix/nvm

**Comment by niczy** [comment]
sorry...

**Comment by jonathanong** [comment]
Oh sorry. Sounded kind of short. Was busy watching house of cards :) Yeah iojs isn't an npm package.

**Pull request closed without merging**
