### PR TITLE
Feat: upgrade querystring to URLSearchParams

### LINKED ISSUE #1570: Platform: upgrade query string to URLSearchParams
https://nodejs.org/api/querystring.html

### PR DESCRIPTION
**Pull request by adaex**
close #1570 

I'm not sure if this is necessary.

### CODE REVIEW

**Comment by jonathanong** [comment]
thanks! looking more into this, do you think it would be better if we just exposed the `URLSearchParams` instance as `ctx.request.searchParams` or something?

yeah, not necessary, but query string is considered legacy

**Comment by adaex** [comment]
@jonathanong 

I think exposed the `URLSearchParams` instance as `ctx.request.searchParams` is a good idea. 

How do you see #1575 ? If there is no problem, I will continue to complete it.

**Review by miwnwski — CHANGES_REQUESTED** [review]
LGTM, but requires some additions.

If you don't mind exposing searchParams as Request#searchParams, and it would be nice to add a line to History.md as well as this is a breaking change. Also a test or two for completeness!

Since this is available from node 10+ it's mergeable once the PR is massaged a bit.

I closed #1575 in favour of this PR.

**Comment by jonathanong** [comment]
merged https://github.com/koajs/koa/pull/1828

**Pull request closed without merging**
