### PR TITLE
refactor Application into an es6 class

### PR DESCRIPTION
**Pull request by tejasmanohar**
basically #512 without merge conflicts.

i only refactored application into es6 classes. request, response, and context don't really make sense as es6 classes to me since they don't have a constructor, i don't know why you'd `new` them... makes more sense as obj literal / proto to me. making a `new Koa()` does make sense semantically though (well, arguably since you probably wouldn't make multiple of them except in unit tests.. or pass args- sounds like a singleton). 

thoughts?

### CODE REVIEW

**Comment by tj** [comment]
whoop!

**Comment by tejasmanohar** [comment]
woohoo

**Comment by targos** [comment]
I wonder if we shouldn't still export a factory function ? This is a big breaking change for users.
I personally don't care as I'm willing to update my current applications to use `new`.

```js
module.exports = function() {
  return new Application();
};
```

**Comment by tejasmanohar** [comment]
@targos we could indeed. that was discussed here- https://github.com/koajs/koa/pull/512#issuecomment-147255796 ... look thru there and drop points here if you think the factory function is still ideal.

**Comment by tejasmanohar** [comment]
@targos 
i don't like to make huge breaking changes either, but in a major version, i don't think it'd be unreasonable to ask users to use the `new` keyword especially when koa is cutting-edge and moving so fast (old users were probably mostly on harmony... i'm sure they're cool w/ change lol)

takeaway: imo, if we're going to return a factory, we probably should skip on classes because this
- breaks `instanceof` and proto
- is unconventional / negates the feature

**Comment by targos** [comment]
Yeah I agree with you.
Please don't revert, I'm glad that there is at least one popular library that doesn't fear to go forward!

**Comment by tejasmanohar** [comment]
:)

though whether classes are _forward_ or not is an interesting question... but enough there lol ;)

**Pull request merged**
